### PR TITLE
Add basic support for CustomFields

### PR DESCRIPTION
**Pull request by mangelajo**

### CODE REVIEW

**Comment by mangelajo** [comment]
Let me know if it makes sense as it is, or if we want something changed. I'm using it as it is.

**Comment by adlio** [comment]
Just got back from vacation. Hoping to review this week. Intending to merge after review.

**Comment by mangelajo** [comment]
thank you, let me know if you believe that some of the interfaces could be
improved. For the custom fields to be usable I needed to create some
helpers that process the raw trello data into something more digestable.

**Comment by mangelajo** [comment]
Thanks @adlio , I had another look to the code in hope of finding a better interface, but I couldn't come up with something better.

I'm using it from here so far: https://github.com/mangelajo/track/blob/master/cmd/trelloListCards.go#L84

**Comment by gesellix** [comment]
I would like to see this merged :)

**Comment by adlio** [comment]
@gesellix Ask and ye shall receive!

**Comment by gesellix** [comment]
@adlio oh, if life would always be so easy :-p
Thanks so much for the quick merge!

**Comment by mangelajo** [comment]
Thank you! :)
---
irc: ajo / mangelajo
Miguel Angel Ajo Pelayo
+34 636 52 25 69
skype: ajoajoajo

**Pull request merged**
