### PR TITLE
feat: AddFileAttachment support

### PR DESCRIPTION
**Pull request by temamagic**
Hi there! Didn't found method for upload attachment not via url, so here it is :)

### CODE REVIEW

**Comment by konsalex** [comment]
Any plans on merging this? I see the repo is pretty inactive, but this feature would be amazing to be included 🚀  I will patch this anyway with the code from @temamagic 🦾

**Comment by temamagic** [comment]
@konsalex  thx

if you need use this method right now, you can use replace in go.mod like this:
```
replace(
	github.com/adlio/trello v1.9.0 => github.com/temamagic/trello v1.9.5
)
```

**Comment by konsalex** [comment]
Thanks @temamagic

**Comment by adlio** [comment]
Apologies for the delay... been busy with other work, but I'm making my way through PR's this weekend.

**Review by adlio — APPROVED** [review]
Thank you for the contribution @temamagic!

**Pull request merged**
