### PR TITLE
feat(label): add create label function

### PR DESCRIPTION
**Pull request by ullayne02**
Adiciona o método para criar uma label no board

### CODE REVIEW

**Comment by adlio** [comment]
HI @ullayne02, thanks for the PR. The code looks right to me, but I haven't had a chance to test it yet.

Would you be willing to add a test case to cover the new code? I'm looking to the test coverage to help aid in debugging future changes to JSON structure Trello might make on their side.

**Comment by ullayne02** [comment]
> HI @ullayne02, thanks for the PR. The code looks right to me, but I haven't had a chance to test it yet.
> 
> Would you be willing to add a test case to cover the new code? I'm looking to the test coverage to help aid in debugging future changes to JSON structure Trello might make on their side.

Sure!! I'll upload the PR.

**Comment by fdcds** [comment]
Is someone still working on this?

**Comment by adlio** [comment]
> Is someone still working on this?

Just merged an updated version with test coverage. Note the method signature changed to:

```go
func (b *Board) CreateLabel(label *Label, extraArgs ...Arguments) error {
```

... to match similar functions like CreateCard.

**Pull request merged**
